// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: sqlite_service.proto

package sqlitepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sqlite_Query_FullMethodName = "/sqlite.Sqlite/Query"
)

// SqliteClient is the client API for Sqlite service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Sqlite wraps an embedded sqlite3 binary over gRPC. The Query RPC
// accepts a typed SqlStmtList (the mechanically-derived CST) or, as a
// transitional escape hatch, a raw SQL string.
type SqliteClient interface {
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
}

type sqliteClient struct {
	cc grpc.ClientConnInterface
}

func NewSqliteClient(cc grpc.ClientConnInterface) SqliteClient {
	return &sqliteClient{cc}
}

func (c *sqliteClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, Sqlite_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SqliteServer is the server API for Sqlite service.
// All implementations must embed UnimplementedSqliteServer
// for forward compatibility.
//
// Sqlite wraps an embedded sqlite3 binary over gRPC. The Query RPC
// accepts a typed SqlStmtList (the mechanically-derived CST) or, as a
// transitional escape hatch, a raw SQL string.
type SqliteServer interface {
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	mustEmbedUnimplementedSqliteServer()
}

// UnimplementedSqliteServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSqliteServer struct{}

func (UnimplementedSqliteServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedSqliteServer) mustEmbedUnimplementedSqliteServer() {}
func (UnimplementedSqliteServer) testEmbeddedByValue()                {}

// UnsafeSqliteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SqliteServer will
// result in compilation errors.
type UnsafeSqliteServer interface {
	mustEmbedUnimplementedSqliteServer()
}

func RegisterSqliteServer(s grpc.ServiceRegistrar, srv SqliteServer) {
	// If the following call panics, it indicates UnimplementedSqliteServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sqlite_ServiceDesc, srv)
}

func _Sqlite_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqliteServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sqlite_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqliteServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sqlite_ServiceDesc is the grpc.ServiceDesc for Sqlite service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sqlite_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sqlite.Sqlite",
	HandlerType: (*SqliteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _Sqlite_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sqlite_service.proto",
}
