// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: sqlite_service.proto

package sqlitepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*QueryRequest_Sql
	//	*QueryRequest_Stmts
	Body          isQueryRequest_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_sqlite_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sqlite_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_sqlite_service_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetBody() isQueryRequest_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *QueryRequest) GetSql() string {
	if x != nil {
		if x, ok := x.Body.(*QueryRequest_Sql); ok {
			return x.Sql
		}
	}
	return ""
}

func (x *QueryRequest) GetStmts() *SqlStmtList {
	if x != nil {
		if x, ok := x.Body.(*QueryRequest_Stmts); ok {
			return x.Stmts
		}
	}
	return nil
}

type isQueryRequest_Body interface {
	isQueryRequest_Body()
}

type QueryRequest_Sql struct {
	// Raw SQL — forwarded verbatim to sqlite3.
	Sql string `protobuf:"bytes,1,opt,name=sql,proto3,oneof"`
}

type QueryRequest_Stmts struct {
	// Typed CST — server must render back to SQL text. Not yet
	// implemented; returns UNIMPLEMENTED until the SqlStmtList → SQL
	// printer lands.
	Stmts *SqlStmtList `protobuf:"bytes,2,opt,name=stmts,proto3,oneof"`
}

func (*QueryRequest_Sql) isQueryRequest_Body() {}

func (*QueryRequest_Stmts) isQueryRequest_Body() {}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Column        []string               `protobuf:"bytes,1,rep,name=column,proto3" json:"column,omitempty"`
	Row           []*Row                 `protobuf:"bytes,2,rep,name=row,proto3" json:"row,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_sqlite_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sqlite_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_sqlite_service_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetColumn() []string {
	if x != nil {
		return x.Column
	}
	return nil
}

func (x *QueryResponse) GetRow() []*Row {
	if x != nil {
		return x.Row
	}
	return nil
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cell          []string               `protobuf:"bytes,1,rep,name=cell,proto3" json:"cell,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_sqlite_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_sqlite_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_sqlite_service_proto_rawDescGZIP(), []int{2}
}

func (x *Row) GetCell() []string {
	if x != nil {
		return x.Cell
	}
	return nil
}

var File_sqlite_service_proto protoreflect.FileDescriptor

const file_sqlite_service_proto_rawDesc = "" +
	"\n" +
	"\x14sqlite_service.proto\x12\x06sqlite\x1a\fsqlite.proto\"W\n" +
	"\fQueryRequest\x12\x12\n" +
	"\x03sql\x18\x01 \x01(\tH\x00R\x03sql\x12+\n" +
	"\x05stmts\x18\x02 \x01(\v2\x13.sqlite.SqlStmtListH\x00R\x05stmtsB\x06\n" +
	"\x04body\"F\n" +
	"\rQueryResponse\x12\x16\n" +
	"\x06column\x18\x01 \x03(\tR\x06column\x12\x1d\n" +
	"\x03row\x18\x02 \x03(\v2\v.sqlite.RowR\x03row\"\x19\n" +
	"\x03Row\x12\x12\n" +
	"\x04cell\x18\x01 \x03(\tR\x04cell2>\n" +
	"\x06Sqlite\x124\n" +
	"\x05Query\x12\x14.sqlite.QueryRequest\x1a\x15.sqlite.QueryResponseB8Z6github.com/accretional/proto-sqlite/sqlite/pb;sqlitepbb\x06proto3"

var (
	file_sqlite_service_proto_rawDescOnce sync.Once
	file_sqlite_service_proto_rawDescData []byte
)

func file_sqlite_service_proto_rawDescGZIP() []byte {
	file_sqlite_service_proto_rawDescOnce.Do(func() {
		file_sqlite_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sqlite_service_proto_rawDesc), len(file_sqlite_service_proto_rawDesc)))
	})
	return file_sqlite_service_proto_rawDescData
}

var file_sqlite_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sqlite_service_proto_goTypes = []any{
	(*QueryRequest)(nil),  // 0: sqlite.QueryRequest
	(*QueryResponse)(nil), // 1: sqlite.QueryResponse
	(*Row)(nil),           // 2: sqlite.Row
	(*SqlStmtList)(nil),   // 3: sqlite.SqlStmtList
}
var file_sqlite_service_proto_depIdxs = []int32{
	3, // 0: sqlite.QueryRequest.stmts:type_name -> sqlite.SqlStmtList
	2, // 1: sqlite.QueryResponse.row:type_name -> sqlite.Row
	0, // 2: sqlite.Sqlite.Query:input_type -> sqlite.QueryRequest
	1, // 3: sqlite.Sqlite.Query:output_type -> sqlite.QueryResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sqlite_service_proto_init() }
func file_sqlite_service_proto_init() {
	if File_sqlite_service_proto != nil {
		return
	}
	file_sqlite_proto_init()
	file_sqlite_service_proto_msgTypes[0].OneofWrappers = []any{
		(*QueryRequest_Sql)(nil),
		(*QueryRequest_Stmts)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sqlite_service_proto_rawDesc), len(file_sqlite_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sqlite_service_proto_goTypes,
		DependencyIndexes: file_sqlite_service_proto_depIdxs,
		MessageInfos:      file_sqlite_service_proto_msgTypes,
	}.Build()
	File_sqlite_service_proto = out.File
	file_sqlite_service_proto_goTypes = nil
	file_sqlite_service_proto_depIdxs = nil
}
